input_dir: "test/"
# fnames: 
#   - "test"
output_dir: "test/"
logs_dir: "logs/humas_hmmer"
benchmarks_dir: "benchmarks/humas_hmmer"
# model: "data/AS-SFs-hmmer3.0.290621.hmm"
model: "data/AS-HORs-hmmer3.3.2-120124.hmm"
thr_ident: 0.7
threads: 12
mem: 4
